### ISSUE TITLE
ValueError: BuilderConfig '405' not found. Available: ['0625', '3M']

### ISSUE THREAD

**Issue by xxrjun** [ShinoharaHare/LLM-Training#5]
Reproduction

```bash
llm-training fit --config phi-3/phi-3-mini_it_example.yaml
```

原解析套件的解析規則應該無法改，解決方法兩種

- 更改資料集路徑名稱，不以 `0` 為開頭，否則會被轉成 Octal Number。
    
    ```yaml
    data:
      class_path: llm_training.data.InstructionTuningDataModule
      init_args.config:
        dataset_kwargs:
          path: ShinoharaHare/Infinity-Instruct-Reformatted
          # name: "0625" # will be converted to an octal number 405 -> failed
          name: "3M" # will be parsed as a normal string -> success
        pre_processed_data_path: null
        tokenizer:
          class_path: HFTokenizer
          init_args:
            path: microsoft/Phi-3-mini-128k-instruct
        batch_size: 1
        add_default_system_prompt_rate: 0.0
        default_system_prompt: ""
        chat_template: phi-3
        concat_method: GROUP_BY_LENGTH
        max_length: 4096
        pad_to_multiple_of: 64
        validation_split: null
        num_proc: 4
        num_workers: 4
        enable_cache: true
    ```
    
- 顯性呼叫（不適合當前框架）
    
    ```python
    from datasets import load_dataset
    dataset = load_dataset("ShinoharaHare/Infinity-Instruct-Reformatted", name="0625")
    ```
